services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      JAEGER_PROPAGATION: w3c
    ports:
      - 16686:16686
      - 4317
    healthcheck:
      test: [CMD, wget, -q, -S, -O, "-", "localhost:14269"]

  collector:
    image: otel/opentelemetry-collector:0.107.0
    volumes:
      - ./otel-collector.yaml:/etc/otelcol/config.yaml
    ports:
      - 4317
    depends_on:
      jaeger:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=psswrd
      - POSTGRES_DB=catalog

  catalog_svc:
    build:
      context: ./catalog_service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DB_URL=postgres://root:psswrd@postgres:5432/catalog?sslmode=disable
      - OTLP_GRPC_ENDPOINT=collector:4317
    depends_on:
      - postgres
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
    command: [ "/app/server" ]

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    entrypoint: redis-server --appendonly yes

  cart_svc:
    build:
      context: ./cart_service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - DB_URL=redis:6379
      - OTLP_GRPC_ENDPOINT=collector:4317
    depends_on:
      - redis

  payment_svc:
    build:
      context: ./payment_service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - OTLP_GRPC_ENDPOINT=collector:4317
    depends_on:
      - cart_svc

  shipping_svc:
    build:
      context: ./shipping_service
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      - OTLP_GRPC_ENDPOINT=collector:4317
    depends_on:
      - payment_svc

  email_svc:
    build:
      context: ./email_service
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - OTLP_GRPC_ENDPOINT=collector:4317
    depends_on:
      - shipping_svc

  order_svc:
    build:
      context: ./order_service
      dockerfile: Dockerfile
    environment:
      - CATALOG_SVC_ADDR=catalog_svc:3001
      - CART_SVC_ADDR=cart_svc:3002
      - PAYMENT_SVC_ADDR=payment_svc:3003
      - SHIPPING_SVC_ADDR=shipping_svc:3004
      - EMAIL_SVC_ADDR=email_svc:3005
      - OTLP_GRPC_ENDPOINT=collector:4317
    ports:
      - "3006:3006"
    depends_on:
      - email_svc

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - CATALOG_SVC_ADDR=catalog_svc:3001
      - CART_SVC_ADDR=cart_svc:3002
      - PAYMENT_SVC_ADDR=payment_svc:3003
      - SHIPPING_SVC_ADDR=shipping_svc:3004
      - EMAIL_SVC_ADDR=email_svc:3005
      - ORDER_SVC_ADDR=order_svc:3006
      - OTLP_GRPC_ENDPOINT=collector:4317
    ports:
      - "4000:4000"
    depends_on:
      - order_svc

